Repository SOPKATHON-LUCKY-SEVEN/back-end-game, pull requests merged in 2022-05, with the labels that each got.

#9 Letter, User 컬렉션 정의
  src/config/index.ts
  src/data/database/configMongoose.ts
  src/data/models/Letter.ts
  src/data/models/User.ts
  src/index.ts
  src/interface/LetterInfo.ts
  src/interface/UserInfo.ts
Labels: ✨ Feature, Nunu, Chaen

#15 [feature/#10] Create Letter 만들기
  src/interface/letter/LetterCreateDto.ts
  src/service/LetterService.ts
  src/service/index.ts
  src/util/BaseResponse.ts
  src/util/PostBaseResponseDto.ts
  src/util/message.ts
  src/util/statusCode.ts
Labels: ✨ Feature, Nunu

#18 [feature/#10] Letter API 만들기
  src/controller/LetterController.ts
  src/interface/letter/LetterResponseDto.ts
  src/router/LetterRouter.ts
  src/router/index.ts
  src/service/LetterService.ts
  src/util/message.ts
Labels: ✨ Feature, Nunu

#19 프로젝트 구조 리드미에 넣기
  README.md
Labels: 📃 Docs, Nunu

#21 [feature/#20] BugFIx
  src/controller/LetterController.ts
  src/controller/index.ts
  src/index.ts
  src/router/LetterRouter.ts
Labels: 🐞 BugFix, Nunu

#17 [feat/#13] UserController Create 처리
  src/controller/UserController.ts
  src/controller/index.ts
  src/index.ts
  src/interface/user/UserResponseDto.ts
  src/router/UserRouter.ts
  src/router/index.ts
  src/service/UserService.ts
  src/util/message.ts
Labels: ✨ Feature, Chaen
